apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: incident-api
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: apps
  storageNamespace: apps
  dependsOn:
    - name: kong
      namespace: flux-system
  chart:
    spec:
      chart: ./helm/incident-api
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: {}
