apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: sundiata-instrumentation
  namespace: apps
spec:
  exporter:
    endpoint: http://opentelemetry-collector.monitoring.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: "true"
      - name: OTEL_LOGS_EXPORTER
        value: otlp
