apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - tasks/git-clone.yaml
  - tasks/lint.yaml
  - tasks/test.yaml
  - tasks/build-push.yaml
  - tasks/update-image-tag.yaml
  - pipeline.yaml
  - trigger/triggerbinding.yaml
  - trigger/triggertemplate.yaml
  - trigger/eventlistener.yaml
